### ISSUE TITLE
Microfoon aanzetten

### ISSUE THREAD

**Issue by vasilisvg** [CMDA/education-from-home#1]
Er staat in [het document over Brightspace](https://github.com/CMDA/education-from-home/blob/master/src/posts/brightspace-features.md) dat studenten hun microfoon niet kunnen gebruiken als ze de externe link gebruiken. Is dat zo? Ik heb namelijk iemand van buiten de HvA een gastcollege laten geven. Die konden we toch echt wel horen.

**Comment by dandevri** [comment]
Voor zover ik weet zijn er twee 'modes' in VCL: `listen only` en `microphone`. Daar komt een pop-up van in beeld zodra je de VCL joint. Als je via de externe linkt joint kun je alleen _listen only_ aanklikken. Waarschijnlijk omdat je niet direct via Brightspace binnenkomt en je dan geen Brightspace account hebt.

**Comment by vasilisvg** [comment]
Toch niet hoor, volgens mij. Astrid Poot heeft college gegeven via zo’n externe link. We hebben haar ook gewoon presenter en moderator rights gegeven. En ik heb met een testpersoon voor de Minor Webdev gesproken via zo’n externe link. Of hebben we het over iets anders?

**Comment by dandevri** [comment]
Je hebt overigens gelijk, ik denk dat het is aangepast. Maar misschien was het altijd al zo :) Je kan nu ook als je met listen only joined daarna switchen naar de microfoon modus.

**Comment by dandevri** [comment]
Nog even een issue een maand later closen, never leave a github issue open.
